[workspace]
members = [
    "crates/sacabase",
    "crates/sacapart",
    "crates/divsufsort",
    "crates/cdivsufsort",
    "crates/divsuftest",
    "crates/dc3",
]

[profile.release]
debug = true


