[package]
name = "cdivsufsort"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[features]
crosscheck = []

[dependencies]
sacabase = { path = "../sacabase" }

[build-dependencies]
cc = "1.0.47"
